### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by khoaho** [thangchung/magazine-website#19]
Hi Thang,

What is the development OS to run docker in this project? Are you using Docker for Windows, Docker Toolbox for Windows or Docker for Linux? The project is built and run at http://localhost:5000/ping

Thank you.
Khoa

**Comment by khoaho** [comment]
I got the project build successfully in Windows 10, but not in Ubuntu 16 LTS. It has error with Cik.CoreLibs for .NETFramework,Version=v4.6. Here is this error in Ubuntu:

> root@ubuntu:~/dev/github/magazine-website/src/Services/Magazine/Cik.Services.Magazine.MagazineService# dotnet build
> Project Cik.CoreLibs (.NETFramework,Version=v4.6) will be compiled because expected outputs are missing
> Compiling Cik.CoreLibs for .NETFramework,Version=v4.6

**Comment by thangchung** [comment]
@khoaho Hi, Khoa. I am using Docker Toolbox for Windows to develop this project. Actually, I created a ubuntu box using Docker Machine and deployed all the published artifacts into that box.
Let me check the latest source code to see why it threw the exception above. I did a lot of refactoring in this time, and not sure it run properly like before. Thank for your report I will get back to you soon.

**Comment by thangchung** [comment]
@khoaho I have a little fixed for docker-compose at [https://github.com/thangchung/magazine-website/commit/9732bee156c427599b1d383abcab8e3798fa734d](https://github.com/thangchung/magazine-website/commit/9732bee156c427599b1d383abcab8e3798fa734d), please have a check. Thanks.

**Comment by khoaho** [comment]
Hi Thang,

I get the latest code and try in three environments: Windows 10, Ubuntu 16 and Docker Toolbox for Windows (with Docker Quickstart Terminal). Here is the result:
- Windows 10: build successfully with `dotnet restore` (at root folder) and `dotnet build` `dotnet run` (at app folders). Windows 10 Home does not support docker.
- Ubuntu 16: fail to run `dotnet build` and `dotnet run` after `dotnet restore`. I also got error to run `docker-compose -f deploy/docker-compose.yml up -d` as it throws error:
  
  > ERROR: In file './deploy/docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
- Docker Toolbox: need some changes in deploy/docker-compose.yml and 4 Dockerfile.\* to allow to build in docker successfully. All the builds work great and all docker images load up after that.

I still don't know how can you create an Ubuntu box with docker-machine. By default docker-machine uses Linux Boot2Docker (https://github.com/boot2docker/boot2docker) to host the docker.

Thank you.
Khoa

**Comment by thangchung** [comment]
@khoaho 

> I still don't know how can you create an Ubuntu box with docker-machine. By default docker-machine uses Linux Boot2Docker (https://github.com/boot2docker/boot2docker) to host the docker.

Sorry this is my fault, it is actually a Linux Boot2Docker :)

> Ubuntu 16: fail to run dotnet build and dotnet run after dotnet restore. I also got error to run docker-compose -f deploy/docker-compose.yml up -d as it throws error:
> 
> ERROR: In file './deploy/docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

I will check it later, but I am quite busy at this time. If possible could you help me on this :+1: 

Regards,
Thang.
