### ISSUE TITLE
Find a solution for centralization the config files into one place like spring cloud config 

### ISSUE THREAD

**Issue by thangchung** [thangchung/magazine-website#3]
Problem: At the moment, the config files put in many places in many projects, then it can make the config duplicated.
Solution: Need a way to central all config files into one place.

**Comment by vutamdung** [comment]
Hi @thangchung,
Seem dose this feature not be applied?

**Comment by thangchung** [comment]
@dungvt Hi Dung, I have done that and config files now put at https://github.com/thangchung/magazine-website/tree/dotnetcore/src/Config, but this project was out of date
